apiVersion: v1
kind: Service
metadata:
  name: cart-mfe
  namespace: ecommerce
  labels:
    app: cart-mfe
spec:
  type: ClusterIP
  selector:
    app: cart-mfe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
