apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: ecommerce
  labels:
    app: analytics-service
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
