const shopfluxPreset = {
  theme: {
    extend: {
      colors: {
        sf: {
          bg:           'var(--sf-bg)',
          'bg-elevated':'var(--sf-bg-elevated)',
          'bg-sunken':  'var(--sf-bg-sunken)',
          'bg-overlay': 'var(--sf-bg-overlay)',
          surface:      'var(--sf-surface)',
          'surface-hover': 'var(--sf-surface-hover)',
          'surface-active':'var(--sf-surface-active)',
          border:       'var(--sf-border)',
          'border-subtle':'var(--sf-border-subtle)',
          'border-strong':'var(--sf-border-strong)',
          text:         'var(--sf-text-primary)',
          'text-secondary': 'var(--sf-text-secondary)',
          'text-tertiary':  'var(--sf-text-tertiary)',
          'text-inverse':   'var(--sf-text-inverse)',
          accent:       'var(--sf-accent)',
          'accent-hover':'var(--sf-accent-hover)',
          'accent-soft': 'var(--sf-accent-soft)',
          success:      'var(--sf-success)',
          'success-soft':'var(--sf-success-soft)',
          warning:      'var(--sf-warning)',
          'warning-soft':'var(--sf-warning-soft)',
          error:        'var(--sf-error)',
          'error-soft': 'var(--sf-error-soft)',
          info:         'var(--sf-info)',
          'info-soft':  'var(--sf-info-soft)',
        },
        neutral: {
          0:   'hsl(0, 0%, 100%)',
          50:  'hsl(220, 20%, 98%)',
          100: 'hsl(220, 16%, 96%)',
          150: 'hsl(220, 14%, 93%)',
          200: 'hsl(220, 13%, 88%)',
          300: 'hsl(220, 10%, 78%)',
          400: 'hsl(220, 8%, 62%)',
          500: 'hsl(220, 6%, 46%)',
          600: 'hsl(220, 8%, 34%)',
          700: 'hsl(220, 10%, 24%)',
          800: 'hsl(220, 14%, 16%)',
          900: 'hsl(240, 6%, 10%)',
          950: 'hsl(240, 8%, 6%)',
        },
      },
      fontFamily: {
        sans: ["'Inter'", '-apple-system', 'BlinkMacSystemFont', "'Segoe UI'", 'Roboto', 'sans-serif'],
        mono: ["'SF Mono'", "'Fira Code'", "'JetBrains Mono'", 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '1' }],
        'xs':  ['0.75rem',  { lineHeight: '1.35' }],
        'sm':  ['0.8125rem',{ lineHeight: '1.5' }],
        'base':['0.875rem', { lineHeight: '1.5' }],
        'md':  ['0.9375rem',{ lineHeight: '1.625' }],
        'lg':  ['1.0625rem',{ lineHeight: '1.35' }],
        'xl':  ['1.25rem',  { lineHeight: '1.3' }],
        '2xl': ['1.5rem',   { lineHeight: '1.25' }],
        '3xl': ['1.875rem', { lineHeight: '1.2' }],
        '4xl': ['2.25rem',  { lineHeight: '1.1' }],
        '5xl': ['3rem',     { lineHeight: '1' }],
        '6xl': ['3.75rem',  { lineHeight: '1' }],
      },
      letterSpacing: {
        tighter: '-0.04em',
        tight:   '-0.025em',
        normal:  '0em',
        wide:    '0.025em',
        wider:   '0.05em',
        widest:  '0.1em',
      },
      spacing: {
        '0.5': '0.125rem',
        '1.5': '0.375rem',
        '2.5': '0.625rem',
        '3.5': '0.875rem',
        '4.5': '1.125rem',
        '13':  '3.25rem',
        '15':  '3.75rem',
        '18':  '4.5rem',
        '22':  '5.5rem',
        '26':  '6.5rem',
        '30':  '7.5rem',
      },
      borderRadius: {
        'xs':  '0.25rem',
        'sm':  '0.375rem',
        'md':  '0.5rem',
        'lg':  '0.75rem',
        'xl':  '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
      },
      boxShadow: {
        'sf-xs':   '0 1px 2px hsla(220, 10%, 20%, 0.05)',
        'sf-sm':   '0 1px 3px hsla(220, 10%, 20%, 0.06), 0 1px 2px hsla(220, 10%, 20%, 0.04)',
        'sf-md':   '0 4px 6px -1px hsla(220, 10%, 20%, 0.07), 0 2px 4px -2px hsla(220, 10%, 20%, 0.05)',
        'sf-lg':   '0 10px 15px -3px hsla(220, 10%, 20%, 0.08), 0 4px 6px -4px hsla(220, 10%, 20%, 0.04)',
        'sf-xl':   '0 20px 25px -5px hsla(220, 10%, 20%, 0.1), 0 8px 10px -6px hsla(220, 10%, 20%, 0.04)',
        'sf-2xl':  '0 25px 50px -12px hsla(220, 10%, 20%, 0.2)',
        'sf-glow': '0 0 20px hsla(346, 84%, 61%, 0.25)',
        'sf-ring': '0 0 0 2px hsla(346, 84%, 61%, 0.3)',
        'sf-inset':'inset 0 1px 2px hsla(220, 10%, 20%, 0.06)',
      },
      transitionTimingFunction: {
        'sf-standard':  'cubic-bezier(0.25, 0.1, 0.25, 1)',
        'sf-enter':     'cubic-bezier(0, 0, 0.2, 1)',
        'sf-exit':      'cubic-bezier(0.4, 0, 1, 1)',
        'sf-emphasized':'cubic-bezier(0.2, 0, 0, 1)',
        'sf-smooth':    'cubic-bezier(0.16, 1, 0.3, 1)',
        'sf-bounce':    'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      transitionDuration: {
        'instant':  '100ms',
        'fast':     '150ms',
        'normal':   '200ms',
        'moderate': '300ms',
        'slow':     '400ms',
        'slower':   '500ms',
        'cinematic':'700ms',
      },
      backdropBlur: {
        'xs':  '4px',
        'sm':  '8px',
        'md':  '12px',
        'lg':  '16px',
        'xl':  '24px',
        '2xl': '40px',
        '3xl': '64px',
      },
      zIndex: {
        'hide':     '-1',
        'raised':   '1',
        'dropdown': '10',
        'sticky':   '20',
        'header':   '30',
        'overlay':  '40',
        'modal':    '50',
        'popover':  '60',
        'toast':    '70',
        'tooltip':  '80',
        'max':      '100',
      },
      keyframes: {
        'sf-fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        'sf-fade-out': {
          from: { opacity: '1' },
          to:   { opacity: '0' },
        },
        'sf-slide-in-right': {
          from: { transform: 'translateX(100%)', opacity: '0' },
          to:   { transform: 'translateX(0)', opacity: '1' },
        },
        'sf-scale-in': {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        'sf-shimmer': {
          from: { backgroundPosition: '-200% 0' },
          to:   { backgroundPosition: '200% 0' },
        },
        'sf-pulse': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'sf-spin': {
          to: { transform: 'rotate(360deg)' },
        },
      },
      animation: {
        'sf-fade-in':       'sf-fade-in 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'sf-fade-out':      'sf-fade-out 0.15s ease-out forwards',
        'sf-slide-in':      'sf-slide-in-right 0.3s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'sf-scale-in':      'sf-scale-in 0.2s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'sf-shimmer':       'sf-shimmer 2s linear infinite',
        'sf-pulse':         'sf-pulse 2s ease-in-out infinite',
        'sf-spin':          'sf-spin 0.7s linear infinite',
      },
    },
  },
};
export default shopfluxPreset;
