apiVersion: v1
kind: Service
metadata:
  name: shell-mfe
  namespace: ecommerce
  labels:
    app: shell-mfe
spec:
  type: ClusterIP
  selector:
    app: shell-mfe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
